// apps/web/app/pages/dashboard.vue
<script setup lang="ts">
const { $authClient, $store } = useNuxtApp()

definePageMeta({
  middleware: ['auth']
})

const { $orpc } = useNuxtApp()

const session = $authClient.useSession()
const privateData = useQuery($orpc.privateData.queryOptions())

</script>

<template>
  <div class="container mx-auto p-4">
    <h1 class="text-2xl font-bold mb-4">Dashboard</h1>
    <div v-if="session?.data?.user">
      <p class="mb-2">Welcome {{ session.data.user.name }}</p>
    </div>
    <div v-if="privateData.status.value === 'pending'">Loading private data...</div>
    <div v-else-if="privateData.status.value === 'error'">Error loading private data: {{
      privateData.error.value?.message }}</div>
    <p v-else-if="privateData.data.value">Private Data: {{ privateData.data.value.message }}</p>
  </div>
</template>

// apps/web/src/routes/_app/dashboard.tsx
import { useQuery } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { getUser } from "@/functions/get-user";
import { orpc } from "@/utils/orpc";

export const Route = createFileRoute("/_app/dashboard")({
  component: RouteComponent,
  beforeLoad: async () => {
    const session = await getUser();
    return { session };
  },
});

function RouteComponent() {
  const { session } = Route.useRouteContext();

  const privateData = useQuery(orpc.privateData.queryOptions());

  return (
    <div>
      <h1>Dashboard</h1>
      <p>Welcome {session?.user.name}</p>
      <p>API: {privateData.data?.message}</p>
    </div>
  );
}
